# Generated by Django 5.2.4 on 2026-03-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_usuario_apellido_usuario_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(db_column='id_categoria', primary_key=True, serialize=False),
        ),
    ]
