# Generated by Django 5.2.4 on 2026-03-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_categoriausuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaUsuario',
        ),
    ]
